<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<UserSecretsId>820a9eb4-9ee0-4a5d-ac48-d8df87007d02</UserSecretsId>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Algolia.Search" Version="7.13.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.Development.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SharedProducts\SharedProducts.csproj" />
		<ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>
</Project>
